---

- name: Configure my workstation using ansible-pull
  hosts: local
  pre_tasks:
    - name: update packages
      package: name=* state=latest

  roles:
    - workstation
    - ansible-pull-cron

