---

- name: Configure my workstation using ansible-pull
  hosts: localhost
  connection: local # or ssh or paramiko
  pre_tasks:
    - name: update packages
      package: name=* state=latest



  roles:
    - workstation
    - ansible-pull-cron

