---

- name: Configure my workstation using ansible-pull
  hosts: all
  user: root
  become: true
  connection: local # or ssh or paramiko
  pre_tasks:
    - name: update packages
      package: name=* state=latest

  roles:
    - workstation
    - ansible-pull-cron

