---

- name: Configure my workstation using ansible-pull
  hosts: localhost
  connection: local
  user: root
  become: true
  become_method: sudo
  vars_files:
    - vars/packages.yml
    - vars/groups.yml
  pre_tasks:
    - name: get the ansible galaxy roles
      command: ansible-galaxy install -r requirements.yml
    - name: update packages
      package: name=* state=latest

  roles:
    - workstation
    - ansible-pull-cron

