
- name: Install package groups
  package:
   name: "{{item}}"
   state: present
  with_items: "{{groups}}"



- name: Install packages
  package:
   name: "{{item}}"
   state: present
  with_items: "{{packages}}"
